[project]
name = "cortesdiesel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AdrianGil", email = "ruben.gil@jalisco.gob.mx" }
]
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.5",
    "pyodbc>=5.3.0",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
cortesdiesel = "cortesdiesel:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
